Ecco.Web/Controllers/TemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecco.Entities;
using Ecco.Web.Data;
using Ecco.Web.Services;
using System.IO;
using Microsoft.Azure.Storage.Blob;
using Ecco.Web.Models;
using Microsoft.AspNetCore.Authorization;

namespace Ecco.Web.Controllers
{
    [Route("Templates")]
    [Authorize(Roles = "Admin")]
    public class TemplateController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly StorageService _storage;

        public TemplateController(ApplicationDbContext context, StorageService storage)
        {
            _context = context;
            _storage = storage;
        }

        // GET: Template
        [HttpGet("")]
        [HttpGet("Index")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Templates.ToListAsync());
        }

        // GET: Template/Details/5
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var template = await _context.Templates
                .FirstOrDefaultAsync(m => m.Id == id);
            if (template == null)
            {
                return NotFound();
            }

            return View(template);
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Template/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("File,Title")] CreateTemplateModel templateModel)
        {
            if (ModelState.IsValid)
            {
                string fileName = templateModel.File.FileName;
             
                //Upload template object
                Template template = new Template()
                {
                    FileName = fileName,
                    Title = templateModel.Title,
                    IsPublic = true
                };
                _context.Add(template);
                await _context.SaveChangesAsync();

                //Upload image to storage
                await _storage.CloudBlobClient.GetContainerReference("templates").GetBlockBlobReference(fileName).UploadFromStreamAsync(templateModel.File.OpenReadStream());

                return RedirectToAction(nameof(Index));
            }
            return View("Index");
        }

        // GET: Template/Edit/5
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var template = await _context.Templates.FindAsync(id);
            if (template == null)
            {
                return NotFound();
            }
            return View(template);
        }

        // POST: Template/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("File,FileName,Title")] Template template)
        {
            if (id != template.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(template);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TemplateExists(template.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(template);
        }

        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var template = await _context.Templates
                .FirstOrDefaultAsync(m => m.Id == id);
            if (template == null)
            {
                return NotFound();
            }

            return View(template);
        }

        [HttpPost("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var template = await _context.Templates.FindAsync(id);
            _context.Templates.Remove(template);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //[HttpGet("Template")]
        //public async byte[] GetTemplate(string fileName)
        //{
        //    var container = _storage.CloudBlobClient.GetContainerReference("templates");
        //    var blob = container.GetBlockBlobReference(fileName);
        //    Directory.CreateDirectory("assets/templates");
        //    await blob.DownloadToFileAsync("assets/templates/" + fileName, FileMode.OpenOrCreate);
        //    return blob.DownloadToByteArray();
        //}

        [HttpGet("Templates")]
        public async Task<List<byte[]>> GetAllTemplates()
        {
            List<byte[]> blobs = new List<byte[]>();
            BlobContinuationToken blobContinuationToken = null;
            var container = _storage.CloudBlobClient.GetContainerReference("templates");
            do
            {
                var results = await container.ListBlobsSegmentedAsync(null, blobContinuationToken);
                blobContinuationToken = results.ContinuationToken;
                foreach (IListBlobItem item in results.Results)
                {
                    Console.WriteLine(item.Uri);
                    string fileName = item.Uri.Segments[item.Uri.Segments.Length - 1];
                    var blob = container.GetBlockBlobReference(fileName);
                    Directory.CreateDirectory("assets/templates");
                    await blob.DownloadToFileAsync("assets/templates/" + fileName, FileMode.Create);
                    byte[] blobData = System.IO.File.ReadAllBytes("assets/templates/" + fileName);
                    blobs.Add(blobData);
                }
            } while (blobContinuationToken != null);
            return blobs;
        }

        private bool TemplateExists(int id)
        {
            return _context.Templates.Any(e => e.Id == id);
        }
    }
}

Ecco.Web/Views/Shared/_Layout.cshtml
@inject UserManager<EccoUser> _userManager 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecco Space</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ecco Space</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                       @if (User.Identity.IsAuthenticated)
                       {
                            var user = await _userManager.FindByNameAsync(User.Identity.Name);
                            if (await _userManager.IsInRoleAsync(user, "Moderator"))
                            {
                                <li>
                                    <ul class="nav nav-tabs">
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Moderator Portal</a>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                                <a class="dropdown-item text-dark" asp-area="" asp-controller="CardManager" asp-action="Index">Cards</a>
                                                <div class="dropdown-divider"></div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            }

                            if (await _userManager.IsInRoleAsync(user, "Admin"))
                            {
                                <li>
                                    <ul class="nav nav-tabs">
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin Portal</a>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                                <a class="dropdown-item text-dark" asp-area="" asp-controller="CardManager" asp-action="Index">Cards</a>
                                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Template" asp-action="Index">Templates</a>
                                                <div class="dropdown-divider"></div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                           }

                           if (await _userManager.IsInRoleAsync(user, "Company Owner"))
                           { 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Company" asp-action="MyCompany">My Company</a>
                            </li>
                           }
                       }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Ecco Space, LLC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>